/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APARENTESES = 9;
  /** RegularExpression Id. */
  int FPARENTESES = 10;
  /** RegularExpression Id. */
  int NOVAVARIAVEL = 11;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 12;
  /** RegularExpression Id. */
  int TIPOFLOAT = 13;
  /** RegularExpression Id. */
  int TIPOBOOLEAN = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int SOMA = 23;
  /** RegularExpression Id. */
  int SUBTRACAO = 24;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 25;
  /** RegularExpression Id. */
  int DIVISAO = 26;
  /** RegularExpression Id. */
  int ELOGICO = 27;
  /** RegularExpression Id. */
  int OULOGICO = 28;
  /** RegularExpression Id. */
  int MAIOR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int VIRGULA = 32;
  /** RegularExpression Id. */
  int FUN = 33;
  /** RegularExpression Id. */
  int READINPUT = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"newVar\"",
    "\";\"",
    "\"float\"",
    "\"boolean\"",
    "\"=\"",
    "\"printOut\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\",\"",
    "\"fun\"",
    "\"readInput\"",
    "<NUM>",
    "<ID>",
  };

}
